### ISSUE TITLE
Handle end-chat when operator close the chat on their side.

### ISSUE THREAD

**Issue by tahahaz1374** [zoho/SalesIQ-Mobilisten-ReactNative#103]
Is there any way to end the chat when the operator ends the chat on their side?
The chat remains open, but we can't send messages anymore.

**Comment by bhahirathan-mb-11956** [comment]
Hi @tahahaz1374,
 
We apologize for the inconvenience. The expected behavior is that when the chat ends from the operator's side, it will immediately be reflected on the visitor's side.
 
To debug this case further, we need to trace it on our side, so please send us your portal, brand, and chat ID details at [support@zohosalesiq.com](mailto:support@zohosalesiq.com).
 
We will be happy to assist you.
 
Regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by bhahirathan-mb-11956** [comment]
@tahahaz1374 , As there hasn't been any recent activity, we're closing this issue for now. If you need further assistance or would like us to revisit this, please don't hesitate to let us know, and we'll be happy to reopen it. In the meantime, check out our latest release.
 
Thank you for understanding. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.
