### ISSUE TITLE
IOS push notification configuration issue

### ISSUE THREAD

**Issue by dieptang** [zoho/SalesIQ-Mobilisten-ReactNative#21]
Today I got new issue for config the ZhoSalesIQ on the IOS for react native with Objective-C. Specifically it not found the function `enablePush` . 

![image](https://user-images.githubusercontent.com/7411097/127123037-37906f83-26e1-46f8-9c02-3177ccc95b7c.png)

At the top, I imported already  `#import <Mobilisten/Mobilisten.h>`

The documentation for React Native for IOS missing much information, please improve it.

**Comment by Rishabh-Raghunath** [comment]
Hello @dieptang, please refer to Step 2 in the documentation [here](https://www.zoho.com/salesiq/help/developer-section/react-native-sdk-mobile-push-notification-ios.html).
Xcode shows an error since there are a few more arguments that are required for the `enablePush` API that have not been added.

**API usage**:
By importing ` #import <RNZohoSalesIQ/RNZohoSalesIQ.h>`
```objc
[RNZohoSalesIQ enablePush:deviceToken isTestDevice:YES isProductionMode:NO];
```

**Comment by dieptang** [comment]
@Rishabh-Raghunath Thanks, working fine now. I was looked on the website but not found.
