### ISSUE TITLE
Business hours setting does not effect for mobile app

### ISSUE THREAD

**Issue by hungkoala** [zoho/SalesIQ-Mobilisten-ReactNative#25]
https://help.zoho.com/portal/en/kb/salesiq-2-0/admin-guide/controls/articles/setup-business-hours#:~:text=In%20Settings%20%3E%20Brands%20%3E%20Your%20brand,by%20moving%20the%20multicolored%20sliders.

**Comment by Angu-G** [comment]
Hi @hungkoala, Can you please elaborate on the issue?

**Comment by hungkoala** [comment]
I followed the instruction above to change working our for my company but did not see anything on the phone app. Customers can chat, sending messages as normal

**Comment by Angu-G** [comment]
@hungkoala, SDK chats will not be missed if you have chosen **None/Infinite** config in the portal under '**_Settings > Brands > YourBrand > Flow Controls > Set Visitor Waiting Time For Mobile/SDK Visitors_**' even though your portal is offline.
This is the feature exclusive for SDK visitors so that you can pick up the chat anytime you are online.

**Comment by Angu-G** [comment]
Hello @hungkoala, It will be helpful for us to debug further if you confirm the config.

**Comment by Angu-G** [comment]
@hungkoala We hope the waiting timer configuration would have cleared your query on business hours. We are closing this issue now. You can write back if you have further queries.
